[package]
name = "hoshi"
version = "0.1.1"
edition = "2024"
repository = "https://github.com/anuraglol/hoshi"

[dependencies]
sqlite = { version = "0.37.3", features = ["bundled"] }

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
